server.port=8080
logging.level.id.ac.polinema.lumajang=DEBUG
app.pesan-sambutan=Mode pengembangan - data masih tersimpan di memori

spring.datasource.url=jdbc:postgresql://localhost:5432/portalku
spring.datasource.username=postgres
spring.datasource.password=123456789

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true